#+TITLE: Membuat hidup lebih sederhana
#+DATE: 2020-03-21
#+LAYOUT: post
#+DRAFT: true
#+TAGS[]: mylife

* Apakah hidup itu rumit atau sederhana?
Hidup. Bisa menjadi rumit atau sederhana.

Hidup bisa menjadi rumit ketika pikiran selalu memikirkan tentang orang lain, bukan diri
sendiri. dan sebaliknya.

* Apa itu minimalism?
Secara sederhana, minimalis adalah gaya hidup hanya dengan menyimpan barang-barang yang memiliki
nilai / kegunaan.

Misal, Lemari yang berisi 15 kaos tapi hanya menggunakan 7 setiap minggunya.
Jika 8 kaos lainnnya disingkirkan, tidak akan terjadi masalah karena 8 kaos itu
tidak memiliki kegunaan.

Untuk membantu menentukan apakah sebuah barang memiliki kegunaan atau tidak,
dapat dilakukan dengan mengajukan pertanyaan berikut.
"Jika barang itu hilang, apakah secara langsung akan membeli barang itu lagi?"

* Minimalis versi sendiri
- Mengisi lemari hanya dengan pakaian yang dipakai
- Menggunakan kasur hanya untuk tidur dan istirahat (no phone)
- Menggunakan handphone hanya sebagai alat komunikasi
