#+TITLE: 5: Membuat 'payments' lebih sederhana
#+DATE: 2020-03-21
#+LAYOUT: post
#+DRAFT: true
#+TAGS[]: mylife

* Apakah 'payments' itu rumit atau sederhana?
'Payment'. Bisa menjadi rumit atau sederhana.

'Payment' bisa menjadi rumit ketika pikiran selalu memikirkan tentang orang lain, bukan diri
sendiri. dan sebaliknya.

* Apa itu minimalism dalam hal 'Payments'?
Secara sederhana, 'Payment' minimalis adalah gaya hidup hanya dengan menyimpan 'card-card' yang memiliki
nilai / kegunaan.

Misal analogi seperti ini, Lemari yang berisi 15 kaos tapi hanya menggunakan 7 setiap minggunya.
Jika 8 kaos lainnnya disingkirkan, tidak akan terjadi masalah karena 8 kaos itu
tidak memiliki kegunaan.

Untuk membantu menentukan apakah sebuah barang memiliki kegunaan atau tidak,
dapat dilakukan dengan mengajukan pertanyaan berikut.
"Jika barang itu hilang, apakah secara langsung akan membeli barang itu lagi?"

* Minimalis versi sendiri
- Mengisi dompet hanya dengan kartu yang bisa dipakai
- Menggunakan kasur hanya untuk tidur dan istirahat (no phone)
- Menggunakan handphone hanya sebagai alat komunikasi


* My version of payment {IAU}
#+BEGIN_SRC js
console.log("hello world");
<script src="https://www.paypal.com/sdk/js?client-id=test"></script>
<script>paypal.Buttons().render('body');</script>
#+END_SRC
** Desktop payment
#+BEGIN_SRC html
<div id="smart-button-container">
      <div style="text-align: center;">
        <div id="paypal-button-container"></div>
      </div>
    </div>
  <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=JPY" data-sdk-integration-source="button-factory"></script>
  <script>
    function initPayPalButton() {
      paypal.Buttons({
        style: {
          shape: 'rect',
          color: 'gold',
          layout: 'horizontal',
          label: 'paypal',

        },

        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{"description":"Sale","amount":{"currency_code":"JPY","value":2.01,"breakdown":{"item_total":{"currency_code":"JPY","value":1},"shipping":{"currency_code":"JPY","value":1},"tax_total":{"currency_code":"JPY","value":0.01}}}}]
          });
        },

        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            alert('Transaction completed by ' + details.payer.name.given_name + '!');
          });
        },

        onError: function(err) {
          console.log(err);
        }
      }).render('#paypal-button-container');
    }
    initPayPalButton();
  </script>
#+END_SRC
** Mobile payment
#+BEGIN_SRC html
<div id="smart-button-container">
      <div style="text-align: center;">
        <div id="paypal-button-container"></div>
      </div>
    </div>
  <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=JPY" data-sdk-integration-source="button-factory"></script>
  <script>
    function initPayPalButton() {
      paypal.Buttons({
        style: {
          shape: 'rect',
          color: 'gold',
          layout: 'horizontal',
          label: 'paypal',

        },

        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{"description":"Sale","amount":{"currency_code":"JPY","value":2.01,"breakdown":{"item_total":{"currency_code":"JPY","value":1},"shipping":{"currency_code":"JPY","value":1},"tax_total":{"currency_code":"JPY","value":0.01}}}}]
          });
        },

        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            alert('Transaction completed by ' + details.payer.name.given_name + '!');
          });
        },

        onError: function(err) {
          console.log(err);
        }
      }).render('#paypal-button-container');
    }
    initPayPalButton();
  </script>
#+END_SRC
