---
title: "Deploy Nestjs Api to Heroku"
date: 2022-05-10T12:20:02+07:00
draft: false
---

* Deploy NEST JS API to local development problem
solution for this 2 problem
** DTO show empty object
https://stackoverflow.com/questions/68645579/why-this-schema-empty-how-to-setting-apiproperty-in-nestjs
** Auth header didn't working
https://github.com/nestjs/swagger/issues/98

* Deploy to heroku
This problem is the same with me
https://github.com/prisma/prisma/issues/12683
the solution is to write config_vars on heroku setting.
because heroku can't read .env file that I put in .gitignore.


I use this solution too because heroku can't use nest cli, so I put NODE_ENV=Productino to false in config_vars
https://dev.to/rosyshrestha/deploy-nestjs-typescript-app-to-heroku-27e

* Deploy postgresql using heroku addons
For this NestJS API, I'm using heroku addons. But I think for the next project is better using mongodb.
https://elements.heroku.com/addons/heroku-postgresql
then update config_vars in heroku using heroku-postgresql link

but when I try the API, it give me statusCode 500 internal server error.

Fixed by updateing Procfile
web: npm run start:prisma:prod
then the package.json
"start:prisma:prod": "npm run prisma:dev:deploy && node dist/main",
